### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by sinanku** [Argent/dotfiles#1]
Hi Benjamin,

My name is Sinan and I am reaching out to you because I am creating an iOS app called Argent and it seems you have the Github repository associated with this name.  I was plan on releasing open source software through this moniker and was hoping to potentially receive permission to use this endpoint. Since the app name, domain, and business have already been formed using this name it would be a great help to be able to release software under a similar scheme.  If not I will find an alternative github organization name.  Thank you for taking the time to read this, I am also attaching a screenshot of the app for reference.

Best,
Sinan

![ag](https://cloud.githubusercontent.com/assets/1269987/15630727/f3fd4502-2514-11e6-946d-0a2dbe92e8cc.png)

**Comment by Argent** [comment]
Hi Sinan,

sorry, but this has been my github username for a long time. I'm not willing to give it up. Nevertheless you can easily create a repository called 'argent' under your github account. So i don't really understand why you would want also a github account with that name.

Cheers,
Ben

**Comment by sinanulkuatam** [comment]
Ok, the reason being any software released under this name would be under an organization called Argent for which I would pay about $25/month for.  It wouldn't be owned under my personal github account name, which would remain unchanged.  I understand if you are still unwilling to separate from the username, perhaps in the future monetary compensation can be discussed and you can name a price.

-Sinan

**Comment by sinanulkuatam** [comment]
One clarification. The app itself will never be open sourced, just the various libraries that were built for its development (UI, API, DevOps layers) over a course of time.  If you like we can also add you as a permanent member of the organization (without read and write repo privileges however)
